server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    static-path-pattern: /**
    resources:
      static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    name: test
    url: jdbc:mysql://47.93.123.132:3306/linear-fitting?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yansdouble
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.linear-fitting.entity
  configuration:
    mapUnderscoreToCamelCase: true

swagger:
  base-path: /**
  title: 'spring-boot-swagger-linear-fitting'
  description: '基于Swagger构建的SpringBoot RESTApi 文档'
  version: '1.0'
